name: Run ci checks
on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - 'main'
      - 'development'
jobs:
  ci-lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: cache-pre-commit
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-3|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}

      - name: install-pre-commit
        run: pip3 install pre-commit

      - name: run-pre-commit
        shell: bash
        run: |
          pre-commit run  --from-ref ${{ github.event.pull_request.base.sha }} --to-ref ${{ github.event.pull_request.head.sha }} --show-diff-on-failure --color always

  java-app-checks:
    runs-on: ubuntu-latest
    steps:

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker Image
      working-directory: java-app
      run: docker build  --build-arg SONAR_URL=${{SONAR_URL}}  --build-arg SONAR_TOKEN=${{secrets.SONAR_TOKEN}} -t java-app:${{ github.head_ref }}.${{ github.sha }} .

  python-app-checks:
    runs-on: ubuntu-latest
    steps:

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build python Docker Image
      working-directory: python_app
      run: docker build   -t python_app:${{ github.head_ref }}.${{ github.sha }} .
